### ISSUE TITLE
Reply to Isaias recent email

### ISSUE THREAD

**Issue by raveling** [avelingrayorg/gba-pm#1]
Reply to Isaias recent email

**Comment by bobbymray** [comment]
Which email? Should at least include email subject to be at all helpful.

**Comment by raveling** [comment]
Good point!
It was his reply to the "Checking in..." Email dated 5 January 2017.
I sent a reply to him, will close it.

I think there's a real art to issue creation which I am still very much learning.

**Comment by bobbymray** [comment]
Is that the email where, among other things, you pointed out the existing dummy content?

**Comment by bobbymray** [comment]
You sent me a draft on 1/5, subject "Isaias Draft", in which you ask "We are curious - are you intending to continue with the GBA dream?" I wasn't CCed on that if you sent it to Isaias.

**Comment by raveling** [comment]
yeah i forgot to CC you.
oopsy.
just forwarded on to you.
xo
